### ISSUE TITLE
Sentry 9 support

### ISSUE THREAD

**Issue by trrbl** [butorov/sentry-telegram#23]
Are there any plans for https://sentry.io/9/ support?

**Comment by metheoryt** [comment]
I have sentry 9 instance with plugin installed, and it works like usual

**Comment by oonid** [comment]
where's the menu to use sentry-telegram?
I have try to search on Project's "legacy integrations" and Organization's "Integrations" both not found.

**Comment by butorov** [comment]
@trrbl, @metheoryt yes, it works fine for Sentry 9 for me. I use the plugin for production.

@oonid check your settings of the sentry's instance. I have "Telegram Notifications" item in "LEGACY INTEGRATION" part.

**Comment by butorov** [comment]
I've just released a new version on PyPI: https://pypi.org/project/sentry-telegram/
With the declared support of Sentry 9.
But keep in mind, please: the support for a new Sentry version - is only in test cases for a new version. Code of the plugin is compatible.
When Sentry will change API and break backward compatibility - I will increase the major version: 0.2 -> 0.3.

@oonid, feel free to open new issue in case of troubles with plugin installation.
