### ISSUE TITLE
More detailed documentation please

### ISSUE THREAD

**Issue by nirmalhk7** [butorov/sentry-telegram#38]
I'm interested in getting notifications for every Sentry error in my project. This appears to be my only hope to notify Sentry errors in Telegram. 

However I'd like more detailed documentation on how to set this up. I have no idea where to install this package (somewhere on Sentry or locally, and if locally how would it work).

**Comment by butorov** [comment]
Hello!

Thank you for your message.

I suppose that you may mean sentry.io - "cloud" version sentry as a service. Is it?
If so, there is no way to use this plugin with cloud-sentry, unfortunately. You may use it with self-hosted Sentry only.

Talking about Sentry.io, you may ask support about the on-demand installation of the plugin, but I'm not sure that the support will be able to do it for you.

**Comment by nirmalhk7** [comment]
I wasn't aware that Sentry has two different versions. Thanks!
