### ISSUE TITLE
Doesnt work on 22.7.0.dev0

### ISSUE THREAD

**Issue by 50l3r** [butorov/sentry-telegram#49]
Versión: 0.4.0
Sentry Version: 22.7.0.dev0

I install & setup Legacy Integration with specific token & chatid but when i try to do a test it doesnt send message.

![](https://i.gyazo.com/735f67733e089c7cd021fabcc9289b51.png)

**Comment by Olegt0rr** [comment]
This repo is abandoned. 
Use this fork: https://github.com/vortland/sentry-telegram

**Comment by 50l3r** [comment]
I see that test message works but only recieve sentry error via email. Telegram Notifications Python3 its enabled on my sentry project but dont send errors.

**Comment by minhhuy1501** [comment]
It's worked from https://github.com/FarazFe/sentry-telegram
Sentry sent an error to telegram when event is captured

**Comment by Elfimova** [comment]
> It's worked from https://github.com/FarazFe/sentry-telegram Sentry sent an error to telegram when event is captured

Have Sentry 22.10.0. Same error. Test message works, but real errors are ignored. Could anyone fix it?

**Comment by Izerrion** [comment]
Seems for different sentry versions it is enough to just perform the following steps:
pip install sentry-telegram  (or any other updated pip package)
docker-compose restart web worker cron sentry-cleanup

For us, however, worked the ["true"](https://develop.sentry.dev/self-hosted/) way of plugins installations and only then all alerts started working correctly: (not only the test notification)

1) place the archive of the plugin inside the requirements.txt file inside the sentry docker directory, e.g:
.../sentry/sentry/requirements.txt:
https://github.com/FarazFe/sentry-telegram/archive/refs/tags/0.5.0.zip

Advice taken from [here](https://github.com/getsentry/sentry-docs/issues/48).

2) Execute steps from official sentry docs and rebuild all containers in docker-compose:

"""
sentry/enhance-image.sh—To install plugins and their dependencies or make other modifications to the Sentry base image, copy sentry/enhance-image.example.sh to sentry/enhance-image.sh and add necessary steps there. For example, you can use apt-get to install dependencies and use pip to install plugins. After making modifications to sentry/enhance-image.sh, run ./install.sh again to apply them.
"""

3) Proceed with plugin configuration as stated inside this repo.
After that notifications should be sent correctly. Don't forget to use updated forks of the plugin depending on your sentry version.

**Comment by ellyx13** [comment]
Sentry version: Sentry 24.1.0.dev0

I try add [this repo](https://github.com/FarazFe/sentry-telegram) into file sentry/enhance-image.sh:
```
#!/bin/bash 

pip install sentry-telegram-notification
```
And i was use Test Plugin in LEGACY INTEGRATIONS successfully, it sent my telegram channel. But when i create error 500 in backend, it didn't send notification to telegram channel, but sentry still receive this error.

**Comment by Izerrion** [comment]
I recommend using webhooks, because this plugin is not actively maintained.

**Comment by vocolboy** [comment]
Hello guys, I rewrite a new one plugin :)

tested on Sentry 24.2.0 & 24.3.0

https://github.com/tianci-sh/sentry-telegram
