### ISSUE TITLE
INSTALLED_APPS modification doesn't work as specified in README

### ISSUE THREAD

**Issue by rutsky** [butorov/sentry-telegram#5]
`INSTALLED_APPS` in tuple [by default in Sentry](https://github.com/getsentry/sentry/blob/8.15.0/src/sentry/conf/server.py#L272), so using `INSTALLED_APPS = INSTALLED_APPS + ['sentry_telegram']` (e.g. in `sentry.conf.py` in docker-sentry setup) as specified in README leads to the following error:

```
TypeError: can only concatenate tuple (not "list") to tuple
```

**Comment by butorov** [comment]
You right, it's my mistake.
@Stranger6667 fixed it at pull request.
