### ISSUE TITLE
Message to topic

### ISSUE THREAD

**Issue by aokhonchenko** [butorov/sentry-telegram#51]
Hello. Could you please add support for topics? Now it look like impossible to send message not just to general level

**Comment by mafuuu-dev** [comment]
@butorov please pay special attention

This is a very important part of the functionality. Without it it’s extremely uncomfortable to use the new features of Telegram. We can say that it’s a blocker

**Comment by butorov** [comment]
Hello @mafuuu-dev, thank you for your attention to the issue. @aokhonchenko, thank you for the feature request.

Starting from now, you can utilize the functionality of sending notifications to Telegram threads/topics in version 0.5.0 of the plugin.

Feel free to drop a comment in case of any further questions.
