### ISSUE TITLE
Display more event details in Telegram message

### ISSUE THREAD

**Issue by rutsky** [butorov/sentry-telegram#6]
Currently only event level is displayed.
It would be nice to see at least short error message.

**Comment by rutsky** [comment]
@bazilio91 I see that you are working on this issue, can you share your progress?

**Comment by bazilio91** [comment]
We are testing extended message layout right now, we'll share it in two or three weeks.

**Comment by bazilio91** [comment]
You can try it too with:
```bash
pip install https://github.com/bazilio91/sentry-telegram/archive/better-errors.zip
```

**Comment by rutsky** [comment]
@bazilio91 I tried your branch, and notification message looks good!

Here is how current `master` and `better-errors` looks like:

![_239](https://cloud.githubusercontent.com/assets/46573/25226523/fec4289c-25cd-11e7-9813-b61cf2cd8b2c.png)

**Comment by bazilio91** [comment]
Backtrace is cropped and not so informative. We'll try to fix it soon.

**Comment by butorov** [comment]
Hello!
It looks like done in #10.
