### ISSUE TITLE
Telegram Notification Error : sentry.safe.method: send_message.process_error in Sentry Version 24.5.1

### ISSUE THREAD

**Issue by sakhihartanto** [butorov/sentry-telegram#61]
Hi, i have an issue Telegram Notification Error on Sentry Version 24.5.1

```
web-1  | Traceback (most recent call last):
web-1  |   File "/usr/src/sentry/src/sentry/utils/safe.py", line 20, in safe_execute
web-1  |     result = func(*args, **kwargs)
web-1  |              ^^^^^^^^^^^^^^^^^^^^^
web-1  | TypeError: TelegramNotificationsPlugin.send_message() got an unexpected keyword argument '_with_transaction'
web-1  | 11:09:25 [ERROR] sentry.safe.method: send_message.process_error
```

Have any idea how to solve it ? one issue have the same problem with me on #60 

Thanks.

**Comment by butorov** [comment]
Hi @sakhihartanto!
Thank you for your attention to the problem.
I fixed it in a just released version 0.6.0. Feel free to give it a try. The fixed version works for me on 24.5.1 (will have the ability to check it on 24.6.0 soon).

<img width="608" alt="Screenshot 2024-06-26 at 1 32 28" src="https://github.com/butorov/sentry-telegram/assets/5171644/407ed1f3-5266-4017-b51a-96644832868b">

I will drop more technical details in #60, which is, as you already mentioned, the same cause.
